name: Upload Python Package to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read  
  id-token: write  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.6' 

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel build twine

      - name: Build the package
        run: |
          python -m build  
      - name: Upload the package to PyPI
        uses: pypa/gh-action-pypi-publish@v2  
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_API_TOKEN }}
