name: Upload Python Package to PyPI

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.6'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine  # Install build tools

    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel  # Create source distribution and wheel

    - name: Upload package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.3.0
      with:
        user: ${{ secrets.PYPI_USERNAME }}  
        password: ${{ secrets.PYPI_API_TOKEN }} 
